//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureInRecording
    {
        public int ProcedureInRecordingID { get; set; }
        public int IDProcedureOfMaster { get; set; }
        public int IDRecording { get; set; }
        public System.TimeSpan Time { get; set; }
        public bool IsCanceled { get; set; }
        public bool IsVisited { get; set; }
    
        public virtual ProcedureOfMaster ProcedureOfMaster { get; set; }
        public virtual Recording Recording { get; set; }
    }
}
