//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedureOfMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcedureOfMaster()
        {
            this.ProcedureInRecording = new HashSet<ProcedureInRecording>();
        }
    
        public int ProcedureOfMasterID { get; set; }
        public int IDMaster { get; set; }
        public int IDProcedure { get; set; }
    
        public virtual Master Master { get; set; }
        public virtual Procedure Procedure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProcedureInRecording> ProcedureInRecording { get; set; }
    }
}
